version: "3.2"
services:

  sql-server-db:
    container_name: "local-sql-server"
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "${DEV_DB_PASSWORD}"
      ACCEPT_EULA: "Y"
      TZ: "America/Los_Angeles"
